### PR TITLE
Use array index instead of Buffer.get

### PR DESCRIPTION
**Pull request by alexbooker**
`Buffer.get` was deprecated in 2013 ([source](https://github.com/nodejs/node/issues/4587)) and removed entirely in Node 6 ([source](https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6#buffer)).

Due to the removal of `Buffer.get` this module fails catastrophically in environments running Node 6.  This impacts me because many modules depend on `bufferjs` (notably[`node-slug`](https://github.com/dodo/node-slug)).

### CODE REVIEW

**Comment by coolaj86** [comment]
Sorry that I'm a lazy bum (or a busy bee, whichever the case may be). Give me your npm username and I'll give you write access there too.

**Comment by alexbooker** [comment]
Hi there AJ,

  

No worries! I know you're **busy** (I heard you say so on a JavaScript Air
episode.)

  

I appreciate you giving me admin access to the repository and my npm username
is [**alexbooker**](https://www.npmjs.com/~alexbooker).

On Jun 1 2016, at 8:35 pm, AJ ONeal &lt;notifications@github.com&gt; wrote:  

> Sorry that I'm a lazy bum (or a busy bee, whichever the case may be). Give
me your npm username and I'll give you write access there too.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly, [view it on GitHub](https://github.com/coolaj86
/node-bufferjs/pull/14#issuecomment-223100755), or [mute the thread](https://g
ithub.com/notifications/unsubscribe/ALYBoF9P65jsthgwilu0mKHHf15N7l1uks5qHd7qga
JpZM4IZLmh).

**Comment by coolaj86** [comment]
Added!

**Comment by alexbooker** [comment]
Thanks, @coolaj86. I'll take care of all this tomorrow.

**Pull request closed without merging**
